STATE_ISO_CODES = {
    'Alabama': 'AL', 
    'Alaska': 'AK',
    'Arizona': 'AZ', 
    'Arkansas': 'AR', 
    'California': 'CA',
    'Colorado': 'CO', 
    'Connecticut': 'CT', 
    'Delaware': 'DE', 
    'Florida': 'FL', 
    'Georgia': 'GA',
    'Hawaii': 'HI',
    'Idaho': 'ID', 
    'Illinois': 'IL', 
    'Indiana': 'IN', 
    'Iowa': 'IA', 
    'Kansas': 'KS',
    'Kentucky': 'KY', 
    'Louisiana': 'LA', 
    'Maine': 'ME', 
    'Maryland': 'MD', 
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN', 
    'Mississippi': 'MS', 
    'Missouri': 'MO', 
    'Montana': 'MT',
    'Nebraska': 'NE', 
    'Nevada': 'NV', 
    'New Hampshire': 'NH', 
    'New Jersey': 'NJ', 
    'New Mexico': 'NM',
    'New York': 'NY', 
    'North Carolina': 'NC', 
    'North Dakota': 'ND', 
    'Ohio': 'OH', 
    'Oklahoma': 'OK',
    'Oregon': 'OR', 
    'Pennsylvania': 'PA', 
    'Rhode Island': 'RI', 
    'South Carolina': 'SC',
    'South Dakota': 'SD', 
    'Tennessee': 'TN', 
    'Texas': 'TX', 
    'Utah': 'UT', 
    'Vermont': 'VT',
    'Virginia': 'VA', 
    'Washington': 'WA', 
    'West Virginia': 'WV', 
    'Wisconsin': 'WI', 
    'Wyoming': 'WY'
}

CLIENT_LOCATIONS = [
    {"name": "West Anchorage High School", "city": "Anchorage, AK", "coords": (61.2163, -149.8997)},
    {"name": "City Hall", "city": "San Francisco, CA", "coords": (37.7793, -122.4193)},
    {"name": "Los Angeles Memorial Coliseum", "city": "Los Angeles, CA", "coords": (34.0141, -118.2879)},
    {"name": "Harrah's Reno (Former)", "city": "Reno, NV", "coords": (39.5296, -119.8138)},
    {"name": "Benson Polytechnic High School", "city": "Portland, OR", "coords": (45.5273, -122.6526)},
    {"name": "Salt Lake Temple", "city": "Salt Lake City, UT", "coords": (40.7707, -111.8910)},
    {"name": "Challis High School", "city": "Challis, ID", "coords": (44.5046, -114.2317)}
]